---
title: "Linear Model"
author: "Miriam Lachs"
date: "2024-11-07"
output: github_document
---

```{r setup, include=FALSE}
library(tidyverse)
library(p8105.datasets)

```


Do some data cleaning 


```{r}
data("nyc_airbnb")

nyc_airbnb = 
  nyc_airbnb |> 
  mutate(stars = review_scores_location / 2) |> 
  rename(
    borough = neighbourhood_group,
    neighborhood = neighbourhood) |> 
  filter(borough != "Staten Island") |> 
  select(price, stars, borough, neighborhood, room_type) %>% 
  mutate(borough = fct_infreq(borough),
         room_type = fct_infreq(room_type))
```

## Fit some models

Start simpple

```{r}

fit = lm(price ~ stars, data = nyc_airbnb)

summary(fit)

names(fit)


coef(fit)

broom::tidy(fit)

fit %>% 
  broom::tidy() %>% 
  select(term,estimate, p.value)

fit %>% 
  broom::glance()


```

TRy a bit more complex

```{r}
fit= 
  lm(price~ stars+borough, data = nyc_airbnb)

fit %>% 
  broom::tidy() %>% 
  select(term,estimate, p.value) %>% 
  mutate(
    term = str_replace(term, "borough",'Borough: ')
  ) %>% 
  knitr::kable()
```

## Some diagnostics 

(backtrack to some EDA)
```{r}
nyc_airbnb %>% 
  ggplot(aes(x=stars, y= price))+
  geom_point()+
  stat_smooth(method = 'lm')
```



Most diagnostics use residual

```{r}
modelr::add_residuals(nyc_airbnb,fit) %>% 
  ggplot(aes(x= resid))+geom_histogram()
```

```{r}
modelr::add_residuals(nyc_airbnb,fit) %>% 
  ggplot(aes(x= borough, y=resid))+geom_violin()+ylim(-100,500)
```


residuals against stars

```{r}
modelr::add_residuals(nyc_airbnb,fit) %>% 
  ggplot(aes(x= stars, y=resid))+geom_point()
```


REsidual against fitted values

```{r}
nyc_airbnb %>% 
  modelr::add_residuals(fit) %>% 
  modelr::add_predictions(fit) %>% 
  ggplot(aes(x=pred,y=resid))+
  geom_point()
```

